apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-postgrest
  namespace: api-auth
spec: 
  acme: 
    server: https://acme-v02.api.letsencrypt.org/directory
    email: islam.muntashir@gmail.com
    privateKeySecretRef:
      name: letsencrypt-postgrest
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prodapi-ingress
  namespace: api-auth
  annotations:
    cert-manager.io/issuer: letsencrypt-postgrest
    cert-manager.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/allow-headers: "true"
    # nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    
spec:
  ingressClassName: nginx
  rules:
    - host: api.muntashirislam.com
      http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postgrest-service
                port:
                  number: 80
  tls:
  - hosts:
    -  api.muntashirislam.com
    secretName: letsencrypt-postgrest-tls
# status:
#   loadBalancer:
#     ingress:
#     - ip: a57354ae823464e5ab24d11a41d60b2f-d0669dd39f00107d.elb.us-east-1.amazonaws.com