apiVersion: v1
kind: Service
metadata:
  name: postgrest-service
  namespace: api-auth
spec:
  selector:
    app: postgrest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP